name: Downloader

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download
      run: wget hhttps://plugins.jetbrains.com/files/6317/487907/lombok-233.14475.39.zip?updateId=487907&pluginId=6317&family=INTELLIJ

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit downloaded files
