name: Downloader
on:
  workflow_dispatch:
    inputs:
      download_link:
        description: 'An url to a file which will be downloaded and added to the repository'
        default: 'https://url-to-file.io'
        required: true
        type: string

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download
      run: wget ${{ inputs.download_link }}

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit downloaded files
