name: Downloader

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Download
      run: wget https://plugins.jetbrains.com/files/6317/502595/lombok-233.14808.21.zip?updateId=502595&pluginId=6317&family=INTELLIJ

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Commit downloaded files
